### ISSUE TITLE
layout of homepage

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#1]
slider and "welcome to geotag-x", find photos and analyse photos should all appear on the one page when people land on the homepage, eg they should not have to scroll down to see "find photos" and analyse photos

**Comment by spMohanty** [comment]
b8fa3705a3f644f5d4976e372e088a400e8b12df fixes this. Is this what you had in mind ?

**Comment by elliec** [comment]
yes thats fine thanks
