### ISSUE TITLE
PyBossa Logo distorted

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#10]

**Comment by spMohanty** [comment]
@elliec  :  I changed the logo to another one, let me know if this one works for you.

**Comment by elliec** [comment]
@spMohanty : The logo you had was fine (i think its more up-to-date than the one on there now), it was just a bit distorted, it looks like its being re-sized

**Comment by spMohanty** [comment]
@elliec : Got it !! Fixed that in e92ca62893a95da080e628f873b2e9b868d990e2 !
