### ISSUE TITLE
Wiki pages for Photos - Yemen project

### ISSUE THREAD

**Issue by tagapic** [geotagx/geotagx-theme#101]
Regarding photos that do not say clearly what the building or place is e.g. a photo of an un-named mosque or other building/s - I am using Google images to identify them by looking at similar images - and then using that information to identify the wiki page and/or location. Sometimes, when identified, the specific building/s in Yemen may not have a wikipedia page, but there may be a wikipedia page for the Governorate. The Nasr Palace in Al Hudaydah (identified through Google Images) does not have its own wiki - but I used the Al Hudaydah goverorate page as the wikipedia page. The wikipedia page does not refer to the Nasr Palace but if the wiki page were updated it would be appropriate. In this case, while there is no Wiki page for the Nasr Palace, I have provide the Al Hudaydah wikipedia page as the reference as it is located in that Governorate. Any thoughts?

**Comment by elliec** [comment]
@tagapic in this case you can use your best judgement, if you think the wiki page is relevant, even if maybe the building is not mentioned you can put it in. Otherwise you can also leave it empty

**Comment by tagapic** [comment]
Thanks, that is fine then.
