### ISSUE TITLE
Yemen Project - Task 3232 and many others - source correction

### ISSUE THREAD

**Issue by tagapic** [geotagx/geotagx-theme#102]
view-source: http://geotagx.org/project/yemenculture/task/3232

The above link goes to page 1 of 26 pages where the image is not listed. The image appears on Page 4. So the link could be either 
http://tinyurl.com/ofveu4r

Or the link could be to image at
The source should be http://tinyurl.com/ofveu4r

**Comment by elliec** [comment]
@tagapic thanks, im not sure if we can fix this because it is automated but I will check with the developer

**Comment by tagapic** [comment]
@elliec, Thanks, when the source of the image is to a page which contains as many as 64 photos, it is difficult to locate it. For photos in this RGS group, all of the URLs in the task list point to a page of the group (it has 1 of 7 or 1 of 64, but does not point to a specific image url ending with a jpg/jpeg.

**Comment by tagapic** [comment]
@elliec 
Task 3420. Image 221 of 1070 source given is http://images.rgs.org/search.aspx?view=&search_ctl%3Akeyword=yemen&search_ctl%3Aimage_type_list=0&search_ctl%3Acollection_list=-1&search_ctl%3AimageSubmit.x=0&search_ctl%3AimageSubmit.y=0&search_ctl%3Adate_range_list=0&search_ctl%3AregionEvent=0&search_ctl%3AdropdownThemes=0&search_ctl%3AsearchPhotographOrPersonShown%3A0=on&search_ctl%3AsearchPhotographOrPersonShown%3A1=on&search_ctl%3Arefine_keyword_field=&isAdvancedSearchDisplay=&search_ctl%3Acollection_choosed=&search_ctl%3AisButtongotoPressed=no

However, the image after some time spent in searching is on page 4 (with each page of 64 images to check before proceeding to the next) and the image url is
http://geotagx.org/project/yemenculture/task/3420.

The photo is that of Al Muhadhar mosque (not identified in RGS, but in Wikipedia).

It would be helpful to have the the link pointing to perhpas the correct page (if not to the specific source page on the site). 
http://images.rgs.org/imageDetails.aspx?barcode=28847

**Comment by tagapic** [comment]
@elliec 
Task 3424. The source link takes you to page 1. The Image is on page 5. http://images.rgs.org/search.aspx?view=&search_ctl%3Akeyword=yemen&search_ctl%3Aimage_type_list=0&search_ctl%3Acollection_list=-1&search_ctl%3AimageSubmit.x=0&search_ctl%3AimageSubmit.y=0&search_ctl%3Adate_range_list=0&search_ctl%3AregionEvent=0&search_ctl%3AdropdownThemes=0&search_ctl%3AsearchPhotographOrPersonShown%3A0=on&search_ctl%3AsearchPhotographOrPersonShown%3A1=on&search_ctl%3Arefine_keyword_field=&isAdvancedSearchDisplay=&search_ctl%3Acollection_choosed=&search_ctl%3AisButtongotoPressed=no

**Comment by tagapic** [comment]
Task 3426. Image 224. The source link takes you to page 1. Search shows image on Page 3. (Image S0012246).

**Comment by tagapic** [comment]
Task 3430, Image 226. This image after a tedious and time consuming effort is on Page 5 of the RGS photo collection. (Image S0019373).

**Comment by elliec** [comment]
@spMohanty maybe this is an issue with how the extension is collecting the source? do you know if it is possible to make it get the exact page on which the image is in search results like this?

**Comment by elliec** [comment]
Closing this - action issue here https://github.com/geotagx/geotagx-chrome-sourcerer/issues/4
