### ISSUE TITLE
Yemen Project - Geo location of Photos

### ISSUE THREAD

**Issue by tagapic** [geotagx/geotagx-theme#103]
Till last week when I was tagging photos, the question "Can you geo-localize the site and/or the photo?" would require me to type in the location below the question... and on typing in the location, this would bring up the place according to the spelling used by the map immediately below. (often different from how it may be spelt in other places and mapping tools). Since Saturday when I was tagging on http://geotagx.org/project/yemenculture/task/3226 I do not see the option for typing a location. Can this now be done only using the search icon in the map?
Thanks,

**Comment by tagapic** [comment]
Is it not possible for the map to take me to the location when I type in the coordinates? What I am doing is when I have the coordinates, I type it in and then use the plus sign to expand map and locate the place. I am drawing a polygon, but not sure what should be the length and breadth of the polygon... Eg. for the old walled city of Shibam. Thanks.

**Comment by elliec** [comment]
@tagapic We have just updated the map to add some improvements but the interface has changed and i can see how it is confusing if you are used to the old one (i had the same problem with the search). The search function on the map should be exactly the same as the old search bar, if you are finding it does not work the same though please let me know. I  know there are some issues with the openlayers search not zooming into locations very well so sometimes they can be hard to fine, we haven't found a way around this yet. Same for the coordinates - someone else asked for this but it seems it is not possible in the version of openlayers we are using. We do have it on our to-do list though.

For the length and breadth of the polygon - just a rough circling of the area you are interested in is fine eg, the edges of the old walled city. It does not have to be exact, don't spend time tracing the boundary! Does that answer your question?

**Comment by elliec** [comment]
@tagapic: @supranove suggested that when the map finds and moves to a location but doesn't zoom in enough, you can use the zoom in and out buttons to zoom into the city and it should zoom down to the correct location (don't use the mouse scroll wheel as that will move the map)

**Comment by tagapic** [comment]
@elliec @supranove, thanks - I see that you have replaced the question with the search icon, I have been using the + sign to locate a photo more closely e.g. Shibam, Tarim, etc where the photo provides the info and also tried the option to open the map widely. It is very tricky to not activate the moving of the map :).  For the ones with only identification as Sana'a I have put a small polygon around the word Sana'a.  I am not sure how I would draw a circle around the "edges of the walled city of Shibam" as I do not know its boundaries. Could you attach a snap shot to illustrate? Thanks.

**Comment by tagapic** [comment]
@elliec I am attaching an image of mapping the polygon...where the photo is from Zabid.
![zabid map illustration](https://cloud.githubusercontent.com/assets/14006578/9634897/ae081f9a-5161-11e5-8ee5-5795f9eb427f.png)

**Comment by elliec** [comment]
@tagapic the boundary of the area that you geotag doesnt have to be exact, unless you know exactly where it is we are happy to have even a rough estimate. When we are at the scale of a whole city or town it is ok if the boundary is not exact.

We get a lot of questions about geotagging so we tried to answer them in a blog http://geotagx.org/project/geotagxblog/11

**Comment by elliec** [comment]
@tagapic the zooming on search issue should now be fixed by @supranove
