### ISSUE TITLE
Photos of street scenes, parts of building, etc.. - Naming and Heritage

### ISSUE THREAD

**Issue by tagapic** [geotagx/geotagx-theme#104]
When images are of street scene, some part of a building, or a house on a street, it is not easy to answer "Do you think there is built heritage in this photo?". Since all these are part of a heritage site, the answer being given by me is Yes.  
On naming, the only way to name them seems to be "House in Sana'a" or "Street scene" or "Old Walled City of Shibam".  
In terms of location, they are either simply Sana'a and if more info is provided Shibam, Zabid etc... 
Here is one example:
![](http://images.rgs.org/webimages/0/0/10000/3000/200/S0013213.jpg)

Any thoughts? thanks.

**Comment by elliec** [comment]
@tagapic that's fine how you are answering. Just give as much detail as you can in the name and the geotagging. I think it would be very difficult, unless you have been to Sana'a, to give much more detail that you have. So something like "Old Walled City of Shibam", or House in Sana'a, is perfectly ok. The same goes for the geotagging. In previous projects we have asked people to drop points where the photo was taken, but that is impossible 95% of the time if you dont know the city, so we just ask you to draw a polygon around the area that you think it is. So if you know it is the old city of Sana'a, draw a polygon around that part of Sana'a, but if you only know that it is somewhere in Sana'a it is perfectly ok to draw a polygon around the whole city. This is still better than no geotagging.

Thanks!
Ellie

**Comment by tagapic** [comment]
@elliec ok thanks.
