### ISSUE TITLE
Project Ebola - Source link

### ISSUE THREAD

**Issue by tagapic** [geotagx/geotagx-theme#111]
@elliec It would be useful to have the Task no. show up on the Screen similar to image numbers.
<b>Incorrect entries posted as "image not clear".</B>

Task 660 - Source link below no longer working
![image](https://cloud.githubusercontent.com/assets/14006578/9737582/54df2310-5615-11e5-8ddc-64e0b75beab9.png)

Task 661 - Incorrect Source link
http://newtelegraphonline.com/ebola-protective-equipment-grossly-inadequate-say-doctors-health-workers/

Task 681 - Incorrect source link
Current incorrect link is http://newtelegraphonline.com/ebola-protective-equipment-grossly-inadequate-say-doctors-health-workers/
<b>Correct link</b> should be (as for task 684) http://who.int/features/2014/ebola-liberia/photos/en/index2.html

Task 683 - link to photo is not visible
Reverse image search and matching led to the following source link (among others) and location as Sierra Leone.
http://www.theguardian.com/world/2015/jan/29/ebola-outbreak-response-enters-endgame

Task 685 - Source link not correct.
<b>Correct</b> link should be http://www.scientificamerican.com/article/ebola-outbreak-prompts-changes-in-protective-equipment/

Task 686 - Incorrect source link (submitted as Liberia though source link not right)
The link http://www.nydailynews.com/news/national/gonzalez-hospital-nurses-claim-lack-ebola-protocols-article-1.1974703 is not correct.
The <B>correct</B> link should be to NY Times http://lens.blogs.nytimes.com/2014/10/26/finding-visible-hope-amid-ebolas-invisible-danger/?smid=go-share&_r=0

Task 687 - Incorrect source link
http://www.doctorswithoutborders.org/our-work/medical-issues/ebola is incorrect and refers to a health worker holding a child.

Task 689 - Source link not matching image
http://www.doctorswithoutborders.org/article/working-together-fight-ebola-sierra-leone
The <b>correct link</b> could be http://www.doctorswithoutborders.org/article/working-together-fight-ebola-sierra-leone. 

Task 694 - Source link not correct
wrong link http://www.thanhniennews.com/health/ebola-vaccine-fully-successful-in-monkey-tests-30855.html. This photo shows a burial team wearing protective clothing, prepare to enter the home a person suspected of having died of the Ebola virus, in Freetown September 28, 2014. (Reuters/Christopher Black) / Reuters.

Task 694, 695, 696, 697 - sources are correct, but just noting regarding location.
- photo location is identified by googling (as for some others) for image instances or by photographer where available in other articles as it is difficult to identify between Sierra Leone, Guinea and Liberia as they are often mentioned together in the article and may seem from any of them. 

Task 698 - Source link not matching the image which is about the Nurse in Spain who is infected with Ebola.
The <b>Correct Link </b> should be http://www.dw.com/en/nurse-in-spain-is-first-person-to-catch-ebola-in-europe/av-17979574

Task 700 - Source link not matching image.
<b>Correct Link</b> should be http://www.doctorswithoutborders.org/article/home-protection-kits-imperfect-neccessary-step

Task 704 - Source link not matching image - gloves drying
The source link did not have the image which is from Guinea.
![image](https://cloud.githubusercontent.com/assets/14006578/9752717/822f3258-5681-11e5-9e8c-29fce70ec73c.png)]
The link to Daily Mail is incorrect. 
http://www.dailymail.co.uk/news/article-2725754/Ebola-vastly-worse-thought-warns-World-Health-Organisation-America-evacuates-diplomatic-families-affected-country.html

Task 705 - Source Link does not match the image.
The image link is http://news.bbcimg.co.uk/media/images/78061000/jpg/_78061813_ebola_virus_disease_outbreak-spl-1.jpg.
The page link (not matching the above image as for 704) is http://www.dailymail.co.uk/news/article-2725754/Ebola-vastly-worse-thought-warns-World-Health-Organisation-America-evacuates-diplomatic-families-affected-country.html

Task 707 - Source link to Daily Mail article does not match the image. Woman adjusting mask of man.

<b>Task 708 and 712 </b>\- Man in yellow suit. Source link to same Daily Mail article does not match the image.  Duplicate Tasks.

Task 716 - Wrong Source Link (repetition from previous Task)

Task 716 - Source Link not matching image of Nurse holding /examining a child.

Tasks 2503, 2505, 2507 are directly linked to image and not to a source.

Task 2503 - image is from Time.com and is from Liberia. The image is referenced in the article http://time.com/3812154/ebola-virus-liberia-daniel-berehulak-nyt/ and is photo 6 of 17.

Task 2505 - should be linked to The Telegraph, UK as image address refers to it. The image of Paye being taken to ambulance is referenced in two Telegraph articles.
http://www.telegraph.co.uk/news/worldnews/ebola/11171614/Thousands-of-children-orphaned-by-Ebola-outbreak.html specifically <b>attributes photo to Sierra Leone </b> and 
http://www.telegraph.co.uk/news/worldnews/ebola/11199589/Ebola-outbreak-Ebola-may-not-be-a-deadly-disease-for-everyone-scientists-find.html

Task 2507 - should be linked to NPR probably as the image address indicates NPR as probable source and location Sierra Leone.
Source Link url could be http://www.npr.org/sections/thetwo-way/2014/07/31/336950373/ebola-patient-will-be-treated-in-atlanta-hospital

**Comment by elliec** [comment]
Action: archive ebola project see issue #124
