### ISSUE TITLE
Ebola Project - Images not matching source

### ISSUE THREAD

**Issue by tagapic** [geotagx/geotagx-theme#113]
@elliec - <b>Task 593 Image 0/104 </b> - the image (of some health workers probably going for decontamination or something) does not match the source link which given.
http://www.thanhniennews.com/health/ebola-vaccine-fully-successful-in-monkey-tests-30855.html
Have marked it as "I do not see a photo".

<b>Task 597 Image 4/104 </b>\- the image of health workers in protection suits does not match the source link given as http://www.dw.com/en/failures-in-the-fight-against-ebola/a-17897009

<b>Task 599 Image 6/104 </b>\- Image of men and women in partially protected wear (gloves, hair covering/cap) does not match the source link given as http://www.doctorswithoutborders.org/our-work/medical-issues/ebola

<b>Task 601 Image 8/104 </b>\- Woman walking by Ebola slogan - Wrong source link
http://www.dw.com/en/failures-in-the-fight-against-ebola/a-17897009 - Source link is child walking by Ebola slogan

<b>Task 602 Image 9/104</b> Wrong source link though no people in the image of "map"

<b>Task 603 Image 10/104</b> Wrong source link though no people in the image of "gloves drying"

<b>Task 604 Image 11/104</b> Wrong source link. Image of health worker adjusting mask of another.
The "correct" source link could be any one of these or other...
http://www.bbc.com/news/world-us-canada-29636355
 http://blogs.cdc.gov/global/2014/09/15/what-its-really-like-fighting-ebola-in-liberia/
http://www.abcnews4.com/story/26856581/local-hospitals-ready-in-face-of-new-cdc-guidelines-for-ebola

**Comment by elliec** [comment]
I went through these photos and the ones in #116 and #111. The project is displaying the correct source image according to the task list csv, so I don't think it is a bug in the project. It could have been one of two things:
- the photos were loaded in before we completely changed the way the platform works, it was really buggy and there could have been a problem in the old system that meant it grabbed the wrong source link
- the project is old and the news sites that were originally showing the photos have changed or been updated, or maybe the photo came from one of the updating stories in the side bars.

**Comment by tagapic** [comment]
thanks @elliec - perhaps this should be taken off public view and reviewed before resharing for tagging?
