### ISSUE TITLE
Ebola Response Project Task 607 Image 14 of 104  - Image and Source Links not matching

### ISSUE THREAD

**Issue by tagapic** [geotagx/geotagx-theme#117]
Have responded to such messages as Image Not Clear.

Image url from the Project Task List appears to be linked to a BBC collection is
http://ichef.bbci.co.uk/news/highquality/590/media/images/78068000/jpg/_78068652_ebola_suit_with_title.jpg

Source link url does not have this image. [Possible the image is one of the Daily Mail articles....]
http://www.dailymail.co.uk/news/article-2725754/Ebola-vastly-worse-thought-warns-World-Health-Organisation-America-evacuates-diplomatic-families-affected-country.html

BBC's link to the image is
http://www.bbc.com/news/health-29518703

**Comment by elliec** [comment]
possibly the image came from an article that isn't shown anymore, will see where else this pops up to confirm

**Comment by elliec** [comment]
like @tagapic suggests, Ebola needs to be archived until we can work out the issues, i think the problem comes from how the old firefox plugin got the source url. This is linked to #98 . once this is solved we can archive Ebola

**Comment by elliec** [comment]
closing this, see #124 for action
