### ISSUE TITLE
Project Yamuna Animals - Project stuck on calculating analyses completed

### ISSUE THREAD

**Issue by ValeErre87** [geotagx/geotagx-theme#121]
A volunteer reported the Yamuna Animals project to be stuck on "Calculating Analyses completed".
She said she was only able to take the tutorial, then the page was stuck on this message (which means she couldn't contribute to the project).

Note: she is using Google Chrome - Version 45.0.2454.101 on Windows 8.1  

![yamunaanimalsstuck](https://cloud.githubusercontent.com/assets/13830929/10607519/4deb3ddc-773a-11e5-8c11-060ee355ced6.JPG)

**Comment by othieno** [comment]
A bit more information: It turns out that access to the image was forbidden (expected in some cases) but nothing was being done to solve the issue on our end. This fix will simply make the project automatically skip any inaccessible images and present the first one it can access to the volunteer :)

**Comment by ValeErre87** [comment]
Sorry Jeremy, but I am a bit confused. What should I have to tell the volunteer? That the bug has been fixed and she can now see all the images? Since she has never contributed to the project before, she should be presented with all the uncompleted tasks of the project. Am I right?

**Comment by othieno** [comment]
Ah, sorry Val, I got too technical. So the bug has been fixed and they can now see all the images we can access. The images that can not be accessed (for instance when the website hosting the image does not exist anymore or has blocked access to the image) are automatically skipped without bothering the volunteers.
