### ISSUE TITLE
Visualisation of Summary of Responses on a Map - Map is not working

### ISSUE THREAD

**Issue by ValeErre87** [geotagx/geotagx-theme#139]
Hi All,
I used this link
http://geotagx.org/geotagx/map-summary/yemeniculturalheritageatrisk

to see the summary of responses for the Yemeni cultural heritage at risk project on a map, but I don't get any results.The map is not uploading the results, which is weird, as I am pretty sure it was working one week ago.

Also, I would like to know if it possible to see the results of the REACH Geotag the Photos project on a map.

**Comment by elliec** [comment]
reach map would be here but its not working either
http://geotagx.org/geotagx/map-summary/emergencyshelterassessmentinthemiddleeast

its a problem with the geojson, it gives an internal server error, eg see
here
http://geotagx.org/geotagx/export/category/emergencyshelterassessmentinthemiddleeast/GeoJSON
