### ISSUE TITLE
tweets should be linked to Geotag-X

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#14]

**Comment by spMohanty** [comment]
@elliec  : So  I embedded a twitter widget to show the geotagx tweets. It doesnt quite go with our theme for now, we will have to either move the tweets sections some other place, or try to collect and render the tweets ourselves.
The advantages of using the twitter widget is that it is maintained by them, and we wont have to worry about any change in the twitter API, also it lets users reply to tweets through the same widget itself.

**Comment by elliec** [comment]
@spMohanty : thats fine, leave it like that for now
