### ISSUE TITLE
task presenter bug

### ISSUE THREAD

**Issue by cobismith** [geotagx/geotagx-theme#146]
Clicking on "You will need to upload the tasks using the CSV importer"  ( http://geotagx.org/project/kavanensblongkomuniti/tasks/import ) yields:

Ooops, Something's wrong

It looks as though we have broken something on our system, sorry

We will try to fix it as soon as we can!

**Comment by othieno** [comment]
Thanks for pointing this out @cobismith! There're a few incompatibilities with our current theme and the recent version of PyBossa. I've opened up a [new issue](147) so they can be tracked in one place. If you do get the dreaded "Ooops, Something's wrong", feel free to add the page to that list!
