### ISSUE TITLE
twitter and github logos

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#15]
Should these be at the top of the page rather than right at the bottom there? Or maybe there is another spot we could put them? Underneath "contact info"? They seem to get a bit lost down there

**Comment by spMohanty** [comment]
@elliec : Well bringing them to the top wont make any sense. and its more like a convention to have links to github/twitter/fb etc around the same place in the footer.
But I have now replicated the information into the contacts sub section in the footer too. Let me know if that works ?

**Comment by elliec** [comment]
@spMohanty : thats fine. However the formatting of the lists has been messed up see terms of use under resources and applications under licenses.

**Comment by spMohanty** [comment]
@elliec : Fixed the layout issues. Please close this issue if it solves the immediate problems we had.
