### ISSUE TITLE
highlight which category has been clicked on

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#17]
can you highlight in some way which category people are in? eg by making the text bold, putting a coloured circle around the image etc?

**Comment by elliec** [comment]
just saw it does have a shadow around the one chosen, can we make this stand out more?

**Comment by spMohanty** [comment]
@elliec : I increased the shadow width and also the width of the border to the circular images. Will this work ?

**Comment by elliec** [comment]
yes this is better
