### ISSUE TITLE
slider styling

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#2]
The slider is too big, it should be resized so that Welcome to geotag-x is not pushed off the screen.
There is a bit too much movement. I think if the background stayed still it would be ok
The background should be removed or be something very plain, there is too much going on with a photo in the back as well as the photos and text ontop, its hard to see what to focus on and i keep trying to look at the background image when we really want people to focus on the projects

**Comment by spMohanty** [comment]
@elliec : Decreased the height of the slider, and made the background static. Though you will have to help me with the picture that goes in the slider background, possibly a high res one, so I can crop it depending on the layout of the slider.
And let me know what else should I change in the slider.

**Comment by elliec** [comment]
@spMohanty : we don't really have any high res images that we could use. For now I would leave it a solid colour until i find something suitable. 

Can you slow down the movement? make it stay on one project for longer

**Comment by spMohanty** [comment]
@elliec : Updated the slider background to a repeating pattern, and made the slide change delay to be 6 seconds.

**Comment by elliec** [comment]
This is better in terms of movement. however I have noticed that the title used in the slider is the project's slug, this should be the Title.

**Comment by spMohanty** [comment]
@elliec : Thanks for pointing that out. Fixed that !! let me know if its okay for now !

**Comment by elliec** [comment]
@spMohanty im still seeing the slug

**Comment by spMohanty** [comment]
@elliec  : My bad again !! Just updated the openstack instance now !!

**Comment by elliec** [comment]
@spMohanty looks good!
