### ISSUE TITLE
logo needed for tab in browser

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#20]
we need to put a logo on the tab in the browser, right now it is just a blank page. maybe a simplified version of the geotag-x logo?

**Comment by spMohanty** [comment]
@elliec  : I added the whole of geotagx logo as a favicon. But as its supposed to be a 16x16 image, the geotagx logo doesnt make much sense up there :( Would you have any ideas about image should we use for the favicon ? I will replace the image with it.

**Comment by elliec** [comment]
I'lll have to think about this, 16x16 is difficult. Ill get back to you

**Comment by spMohanty** [comment]
@elliec : You could also go for 32x32, most browsers these days do support 32x32 favicon, but 16x16 is the de facto standard usually !!
