### ISSUE TITLE
buttons on applications dont stand out enough and should be bigger

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#21]
When i hover over an application and the buttons to start, tutorial, info etc pop up they are greyed out, they should stand out more.

The info, tutorial and settings buttons are too small. I couldnt work out where to click to get info when i first looked at it

**Comment by spMohanty** [comment]
@elliec : I made all the buttons bigger, and also added a tooltip to the individual buttons. Let me know if this works, but I personally like the icons smaller better. We could experiment with smaller icons + tooltip too if you want.

**Comment by elliec** [comment]
@spMohanty : They look better smaller but its not clear where to click. I know what im looking for and it still took me a bit too long to work it out, its much quicker now that they are bigger, and the tutorial is much more obvious which is really important. Though if you want to play around with smaller icons/tooltips thats fine if it works.

**Comment by spMohanty** [comment]
@elliec : Yeah right, the buttons look way better when they are smaller. I think trying to come up with a contrast with the background will solve the issue of usability.
I will push some changes which should make them look like in the image below.
![](http://i.imgur.com/CaW3T6n.png)

**Comment by spMohanty** [comment]
@elliec : Reverted back to small icons and also added a background for clarity. Let me know if this works.

**Comment by elliec** [comment]
@spMohanty background makes a huge difference, looks good like this. The icons still seem a bit greyed out but i dont think thats all that important now you have the background
