### ISSUE TITLE
project page layout

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#23]
Because the top section is dominant and moves whenever i click on the "info" "tasks" "statistics" links at the top i didnt notice that the text at the bottom was changing and thought there was a bug and the links wernt working. This is particularly bad on a smaller screen.

can we do something to make it more obvious that there is text underneath? maybe if the blue banner didnt go all the way across the page but stopped in line with the geotag-x logo and the sign in link it would be less dominant?

Or when you click on info, tasks etc it scrolls you down to that section of the page?

**Comment by spMohanty** [comment]
@elliec : I pushed some changes, which lets the user hide/show the Project details block on all the sub pages of the Project page by clicking on the project title. The block is open by default on the `info` page and it is closed by default on the rest of the pages.
Let me know if this solves this problem.

**Comment by elliec** [comment]
@spMohanty : Looks ok for now but i think it needs to be checked once we have some real content in there. The blue banner could be made a bit narrower to minimise the about info being pushed off the page. But lets wait and see what it looks like with real content

**Comment by spMohanty** [comment]
@elliec : Now that we have the real data from projects migrated, can check if the blue banner looks okay to you ?
(My whole idea was to have a **huge** banner which gives the summary of the project, while still atleast showing the heading of the content of the rest of the page so that the user knows where to go if he wants more details)

**Comment by elliec** [comment]
@spMohanty that looks better now there is content. However the text is all in the righthand column, it looks a bit strange and seems really long, is it possible to make it go across the whole page? is there a reason you have it in a column like that?

**Comment by spMohanty** [comment]
@elliec : Now the description should be full width.

**Comment by elliec** [comment]
@spMohanty looks heaps better
