### ISSUE TITLE
delete only task responses and not tasks

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#24]
is it possible to have a button to delete only the tasks responses and not the tasks.

When we are testing an app we end up with lots of responses that mean nothing and it would be nice to have a button that deletes these before the app is released

**Comment by spMohanty** [comment]
@elliec : Sure that should be possible. But as this would require changes to the pybossa core code. I would send a pull request to the pybossa core dev team, and when they merge it, we will be able to use it. I will update this thread when its done.

**Comment by spMohanty** [comment]
This same issue has also been put up as a feature request on the official pybossa issue tracker. [https://github.com/PyBossa/pybossa/issues/1065]

**Comment by spMohanty** [comment]
@elliec : https://github.com/geotagx/pybossa/commit/065c10376f507e3d9d350a6d0bcdd6f2f16b63df , https://github.com/geotagx/pybossa/commit/2a0b9df94d4a2a63339c153acacc375c1b25a5c1 , https://github.com/spMohanty/geotagx-theme/commit/9ea10fd5ee63623cb25fdd0e2b46b41a7e0e5f71 , https://github.com/spMohanty/geotagx-theme/commit/f69bdd0764432ff7d34685eb1716348500793e89   implement this feature.  
now you should see a button called as `Flush Task Runs` in `Project > Settings > Task Settings` which will let you delete all the task runs associated with the project after a confirmation.

**Comment by elliec** [comment]
@spMohanty thanks seems to work fine. im closing this
