### ISSUE TITLE
remove spam question from applications

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#25]
Lets remove the spam question from the applications for now? i dont think we will get any spam at the moment because the plugin isnt working, and maybe there is a better way of doing it.

What do you think?

**Comment by spMohanty** [comment]
@elliec : Moved this issue to the geotagx_project_template repository, as it discusses an issue from that project. The new issue link can be found at : https://github.com/spMohanty/geotagx_project_template/issues/4
