### ISSUE TITLE
encourage people to sign in/create account

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#30]
The "oops you are anonymous" does not stand out enough. could we have some sort of pop-up somewhere when people are anonymous asking them to create an account? Eg what we discussed just before i went away?

**Comment by spMohanty** [comment]
@elliec : What I can do is, for anonymous users, on every page load, I can start a modal(what you see when you click the `help button` inside an application) with a probability `p=0.2` (from all the page loads done by an anonymous user, 20% of the time the user will get a modal urging him to sign in/create an account, though its not compulsory, he can simply close the modal and do whatever he was upto.

Deciding on the value of `p` will be upto you, as you wouldnt want this reminder to be soo intrusive that the user finds it irritating.

**Comment by elliec** [comment]
@spMohanty : yes please go ahead and do that. I would have it pop up once during a session, eg when they first click on a project. What do you think?

**Comment by spMohanty** [comment]
@elliec : Now you should be able to see a popup reminding anonymous users to sign in when they start contributing to a task.
(If you want this popup on any other pages, let me know)

**Comment by elliec** [comment]
@spMohanty Looks good - two comments
- the sign in button doesn't work and the "Sign in now!" link redirects to the task which then re-opens the pop up.
- can you put a button to "create an account"

**Comment by spMohanty** [comment]
@elliec : Resolved both the issues !! The reason was the pybossa flash messages suddenly stopped removing links after I pulled in all the latest changes from the pybossa official repository today.

**Comment by elliec** [comment]
@spMohanty looks great! I found another typo. On the ~~sign in~~ `create account` page it says "By click the Create account...." This should say "By clicking the Create account..."

**Comment by spMohanty** [comment]
@elliec : It shows correct for me ??? 
![screenshot](http://i.imgur.com/jU9vm3C.png)

**Comment by spMohanty** [comment]
@elliec : Thanks for pointing it out. Fixed that !!
