### ISSUE TITLE
about page

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#31]
The formatting here needs to be fixed
- the filter picture needs to be moved down a line
- disaster response efforts.... should be moved down underneath "what is geotag-x"

im not sure we can really call this citizen science either, its crowdsourcing really. we should put some text about learning here instead, or tweak the citizen science text to reflect what we are doing.

I will come up with the text and find a photo

**Comment by spMohanty** [comment]
@elliec : Implemented the above two layout changes as mentioned by you. Let me know if these would work. Also, do send me the text for the `crowdsourcing` section and the photo(s) for the carousel, after that we can close this issue.

**Comment by spMohanty** [comment]
@elliec : Updated the content you sent via mail. Let me know if this looks good.

**Comment by elliec** [comment]
@spMohanty looks good just fix the formatting of "other ways to participate" to match the rest of the page

Thanks!

**Comment by spMohanty** [comment]
@elliec : Done :)

**Comment by elliec** [comment]
@spMohanty the text on "who are our volunteers" overlaps the picture when the window is a bit minimised.

**Comment by spMohanty** [comment]
@elliec : Should be fixed now :D

**Comment by elliec** [comment]
great thanks!
