### ISSUE TITLE
participation in research question missing from sign-up

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#32]
dont forget to incorporate the participation in research question at sign up, and the surveys

**Comment by spMohanty** [comment]
@elliec : I implemented the survey workflow for the new version of geotagx.  
The backend for this workflow has been implemented in our version of pybossa in the commit https://github.com/spMohanty/pybossa/commit/1289585f2e1c81743d0b2a33881a322262138abb  
This commit tries to make sure there will be **minimal** merge conflicts when you pull changes from the pybossa core in the future. It uses a `geotagx` namespace to make sure our changes remain separate from the pybossa core changes.

Coming back to the survey workflow, the limit of the number tasks required for the `FINAL_SURVEY` to appear has been made configurable, and can be configured by using the parameter `GEOTAGX_FINAL_SURVEY_TASK_REQUIREMENTS = 5` in `settings_local.py` in the pybossa root folder. (The default value has been set to 30, and for our current testing server the parameter has been set to 5 )

Also, for better performance, this implementation uses the **cached** user contribution data to decide when to show the surveys, so it might be a headache during testing, so while testing if you want to reset the cache, you can simply log onto the server and execute `echo "FLUSHALL" | redis-cli`

Let me know if this works. Ideally if you create a new account, after signing it, it should show you the first form. Then after completing the first 5 tasks(and after either waiting for the cache to be refreshed automatically or manually refreshing cache), it should show you the final form if you havent opted out during the first survey.

@supranove : You might have to help @elliec while testing this, if she is stuck by chance.

**Comment by spMohanty** [comment]
@elliec : One minor/major issue we might face now is, when our site is on HTTPS, the browser doesnot let any `iframe` load from a HTTP survey link. So I moved all the survey links to HTTPS, but then `tecfalabs.unige.ch` where the survey forms are hosted currently, uses a self signed SSL certificates :cry: , and both chrome and mozilla do not like that either :sob:, they say that its an untrusted connection and do not even let you add an exception because its within an iframe :cry: 
(Though for now you can test by just closing the popup, it just assumes you honestly filled up the survey)

**Comment by elliec** [comment]
@spMohanty Im not at CERN at the moment, I'll have to check on wednesday when im back. If @supranove gets some time could he check it for bugs? Ill check the workflow when im back wednesday

**Comment by elliec** [comment]
@spMohanty looks fine, lets see what Julien says about the certificate issue. Worst case we just turn the surveys into projects on Geotag-X but I would prefer to avoid that as they are currently responsible for the surveys making it one less thing we have to deal with..

**Comment by spMohanty** [comment]
Closing this issue, as the remaining issue are related to enforcing HTTPS, which should be taken up in a separate issue.
