### ISSUE TITLE
about photo resizes to be really big when browser window is small so it fills the whole window

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#39]

**Comment by spMohanty** [comment]
@elliec :: Do not quite get a sense of the issue ? Can you please elaborate ?

**Comment by elliec** [comment]
@spMohanty open the about page and then make your browser window smaller and you should see what i mean

**Comment by spMohanty** [comment]
@elliec : Yeah thats because of trying to have as much support for mobile devices as possible. But by all means, do we even need that image carousel on the about page , especially when we wont have time to sort through and select good photos to put up there ?

**Comment by elliec** [comment]
@spMohanty no you can get rid of it

**Comment by spMohanty** [comment]
@elliec : Removed the image carousel from the about page !! Hope this solves the issue !!
Though if you make the browser window very small, the CSS framework we use will automatically re order stuff so its more suited for small screens.
