### ISSUE TITLE
button for "projects"?

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#4]
Do you think we should have a button for something like "i know what im doing take me to the projects" next to "find photos" and "analyse photos". Or do you think people will know to scroll down?

**Comment by spMohanty** [comment]
The `Projects` button in the Menu bar on the top is for the same purpose. Do you want to add another button next to the Find Photos and Analyse Photos buttons on the front page ?

**Comment by elliec** [comment]
no thats fine, thanks i forgot about that
