### ISSUE TITLE
getting stuck on second photo

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#41]
there is a bug in pybossa where it gets stuck on the second photo. So a user goes through the application for the first photo, submits his answers and then gets presented with the second photo. He goes through the questions again with the second photo but when he submits, the photo doesn’t change but the application goes back to the first question like it should, it then gets stuck on the second photo no matter how many times you go through the questions and submit. I can only get this in IE however I have had others tell me they also see it in other browsers (thought I can’t replicate it ). Ive noticed the same bug on crowdcrafting.

**Comment by spMohanty** [comment]
This issue can be replicated in IE version `11.0.9600.17728` as pointed out by @elliec

**Comment by elliec** [comment]
and chrome 41.0

**Comment by spMohanty** [comment]
@elliec : Given you can replicate this issue, it would be great if you can check if the new project codes generated by the geotagx-template are also affected by this bug.

**Comment by elliec** [comment]
In the new version, photos do not appear in IE. It seems it does not show it maybe because it is not secure content, I get the pop-up saying it is only showing secure content but when i tell it to show everything it still doesnt appear. 

I had a look at a project on crowdcrafting that is also getting photos from flickr and dont seem to get the same error

**Comment by spMohanty** [comment]
@elliec : Crowdcrafting is not hosted over https, probably for the very same reason :(

**Comment by spMohanty** [comment]
Unable to replicate this issue in IE version `11.0.9600.17633`

**Comment by elliec** [comment]
@spMohanty got feedback that this is happening in Chrome Version 43.0.2357.130 m. Project: "Crop identification for drought"

**Comment by spMohanty** [comment]
@elliec : I would wait till the new error handling thing @supranove is working on, is released. I have a feeling that will handle this and other such similar bug reports that we have been getting.

**Comment by othieno** [comment]
@elliec @spMohanty I'm closing this because it is most likely related to #96.
