### ISSUE TITLE
project icons bigger

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#42]
Can you try making the project icons bigger? they seem a bit small at the moment

**Comment by spMohanty** [comment]
You mean the circles on the front page ?

(I have been using pybossa's nomenclature for consistency. With the circles on the front page being called as 'category' and the tiles on the front page being called as apps/project)

**Comment by elliec** [comment]
yeah thats the ones, maybe just see how they look bigger? right now there seems to be alot of white space around them

**Comment by spMohanty** [comment]
@elliec : Made the project icons a bit bigger. Did you have something at this scale in mind ? or probably as big as the tiles we have below them ?
(these are supposed to be kind of selectors which the users use to filter through the tiles below, hence I would keem them smaller by a margin from the tiles)

**Comment by elliec** [comment]
@spMohanty definitely they should be smaller than the tiles below. I just thought there seemed to be a lot of white space around them. I cant see any difference in the size though (ive opened it in a new browser so it shouldnt be cached)

**Comment by spMohanty** [comment]
@elliec : My bad !! I had not updated the changes on the openstack instance !! you can check them now, I made the individual icons bigger by about 50% in the previous commit references in this thread.

**Comment by elliec** [comment]
@spMohanty ok thats better now i can see them! looks fine like that thanks
