### ISSUE TITLE
Community Page and Leaderboard

### ISSUE THREAD

**Issue by spMohanty** [geotagx/geotagx-theme#43]
Add Community Page and Leaderboard

**Comment by elliec** [comment]
Ive been reading some of our feedback and this was one item that has come up a bit, could we make this a higher priority?

**Comment by spMohanty** [comment]
@elliec : Added a community page of all registered and active users. Active users are the users who have submitted a response to at least one task.
You will notice that the pagination does not work properly for now, that is because of a bug in pybossa, for which I have submitted a pull request (https://github.com/PyBossa/pybossa/pull/1091) 

Also, the community page currently says that we have 206 active registered users, but thats also again because of the pybossa bug, and it will change to 46 active registered users after we have our pull request merged.

TO-DO :
- ~~Add Gravatar support for users who have not uploaded a profile image~~
- ~~Adds leaderboard~~
- Better theming of both the community page and the leaderboard

**Comment by elliec** [comment]
@spMohanty could we clean out the testing accounts? there will be some that appear in the community page and it looks a but messy

**Comment by spMohanty** [comment]
@elliec : Most of the testing accounts are cleaned up. Should look good now.

**Comment by elliec** [comment]
@spMohanty sorry i forgot to mention that i went through and delted them after you added the option to delete users, thanks!
