### ISSUE TITLE
Automated tutorial creation

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#45]
Automate the creation of an application's tutorial should be possible as all of the questions and help etc are already there in the application

ideally in the end a volunteer would have the possibility of doing more than one photo as a tutorial and then would be presented with a "test my knowledge" type of question after they have completed a certain number of tasks

**Comment by spMohanty** [comment]
Moved this issue to https://github.com/spMohanty/geotagx_project_template/issues/9
