### ISSUE TITLE
featured projects is broken

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#5]
When i click on Featured projects under the Admin Site, i get the Oops, Something is wrong error page.

Once this is working would the featured projects appear in the slider and at the top of the list of all projects?

**Comment by spMohanty** [comment]
Fixed the broken featured projects page. 
TO-DO:
1) Fix rendering of the individual project tiles to go with the theme
~~2) Link the featured projects to the projects shown on the front page slider~~
3) Show featured projects at the top of the front page grid.

**Comment by spMohanty** [comment]
@elliec : Should I display the featured projects at the top of the front page grid ? My only concern was, most users will see probably the first two rows of the front page project grid. And having featured projects always appear on the top will have the grid look monotonous and static across multiple page loads. The featured projects are anyway getting all the due attention from the top slider. And having a random shuffling of all the projects in the front page grid across multiple page loads will ensure all projects kind of get some visibility to every user across multiple page loads.
but upto you, it is straight forward to implement.

**Comment by elliec** [comment]
@spMohanty leave it as it is for now, we can always change it later if need be

**Comment by elliec** [comment]
@spMohanty Im closing this as i think it is fine as is
