### ISSUE TITLE
Offset needed for About and Help link

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#53]
when you click on them it scrolls too far down the page

**Comment by spMohanty** [comment]
@elliec : The description of the problem is not quite clear. Can you please provide more details about where exactly do you see this issue ?

**Comment by spMohanty** [comment]
@elliec : Added offset to the `Find Photos` and `Analyse Photos` link on the front page, and the `What is Geotagx` and `Who are our volunteers` links on the About page. I could not exactly find a `Help` link which used in-page links, but let me know if there are other links like these that I missed.

**Comment by elliec** [comment]
@spMohanty thats fine, i think i made a mistake writing help, it should have been find and analyse
