### ISSUE TITLE
GeotagX surveys not registering that the user completed the survey in some cases

### ISSUE THREAD

**Issue by spMohanty** [geotagx/geotagx-theme#57]
We have had reports that, some users are getting stuck on the surveys page, as it is not able to save that the user indeed took the survey.

**Comment by elliec** [comment]
ellie to check

**Comment by elliec** [comment]
@spMohanty feedback from GISCorps volunteer that they were not shown the final survey

How can I get to the surveys? I have completed all tasks.
Michel Bohorquez    michelbohorquez1@gmail.com
(note: he has completed 165 tasks)
