### ISSUE TITLE
Summarization of Task Runs

### ISSUE THREAD

**Issue by spMohanty** [geotagx/geotagx-theme#58]
@elliec , @supranove   : https://github.com/geotagx/geotagx-theme/commit/48e0ebeae4180060e9d1db6cc8ba1a99b037759b and https://github.com/geotagx/pybossa/commit/4505fe53262280b7e53a3d6c15f05add820801df implement the summarization and visualization of the TaskRuns. You might find some noise in the task run summaries, and that is mostly because of the projects where the old data collection schema and the new data collection schema do not match.
A sample visualization page can be seen at : http://geotagx.org/geotagx/visualize/wintershelter/854

And the generic way to access the visualizations is `Project Page > Tasks > Browse Tasks > See Summary of Tasks`

TODO : Figure out how to summarise the geolocation question types. 

@supranove : If you are trying to pull in these commits, you will also have to include this in your `settings_local.py` at the end :

``` python
import json, os
GEOTAGX_SUPPORTED_PROJECTS_SCHEMA = {
  'ebola' : json.loads(open(os.path.dirname(__file__)+'/pybossa/themes/geotagx-theme-v2.0/projects/geotagx-project-ebola/project.json', 'r').read()),\
  'geotagebola' : json.loads(open(os.path.dirname(__file__)+'/pybossa/themes/geotagx-theme-v2.0/projects/geotagx-project-ebola-geotag/project.json', 'r').read()),\
  'reach_geo' : json.loads(open(os.path.dirname(__file__)+'/pybossa/themes/geotagx-theme-v2.0/projects/geotagx-project-middle-east-reach-geotag/project.json', 'r').read()),\
  'wintershelter' : json.loads(open(os.path.dirname(__file__)+'/pybossa/themes/geotagx-theme-v2.0/projects/geotagx-project-middle-east-winter-shelters/project.json', 'r').read()),\
  'animals' : json.loads(open(os.path.dirname(__file__)+'/pybossa/themes/geotagx-theme-v2.0/projects/geotagx-project-somalia-animal-identification/project.json', 'r').read()),\
  'cropid2' : json.loads(open(os.path.dirname(__file__)+'/pybossa/themes/geotagx-theme-v2.0/projects/geotagx-project-somalia-crop-identification/project.json', 'r').read()),\
  'animal2013' : json.loads(open(os.path.dirname(__file__)+'/pybossa/themes/geotagx-theme-v2.0/projects/geotagx-project-yamuna-animals-2013/project.json', 'r').read()),\
  'yamuna_waters' : json.loads(open(os.path.dirname(__file__)+'/pybossa/themes/geotagx-theme-v2.0/projects/geotagx-project-yamuna-floodwaters-2013/project.json', 'r').read()),\
  'geotag_yamuna' : json.loads(open(os.path.dirname(__file__)+'/pybossa/themes/geotagx-theme-v2.0/projects/geotagx-project-yamuna-geotag-2013/project.json', 'r').read()),\
  'yamuna_people' : json.loads(open(os.path.dirname(__file__)+'/pybossa/themes/geotagx-theme-v2.0/projects/geotagx-project-yamuna-people-2013/project.json', 'r').read()),\
  'yamuna2013_poll' : json.loads(open(os.path.dirname(__file__)+'/pybossa/themes/geotagx-theme-v2.0/projects/geotagx-project-yamuna-pollution-2013/project.json', 'r').read()),\
  'shelter2013' : json.loads(open(os.path.dirname(__file__)+'/pybossa/themes/geotagx-theme-v2.0/projects/geotagx-project-yamuna-shelter-2013/project.json', 'r').read()),\
  'geotag_yemen' : json.loads(open(os.path.dirname(__file__)+'/pybossa/themes/geotagx-theme-v2.0/projects/geotagx-project-yemen-geotag/project.json', 'r').read())}
```

**Comment by spMohanty** [comment]
@elliec , @supranove : Should we include the link to these visualizations for every task somewhere in the task presenter ?

**Comment by elliec** [comment]
@spMohanty its best where it is. We want to avoid influencing peoples answers by showing them what others have said. In the results summary that we share under tasks I would allow people to only see results for those photos that have been completed according to the redundancy (eg 20 people have looeked at them)

**Comment by spMohanty** [comment]
@elliec : The results for incomplete tasks are not shown now. It waits till all the task runs are complete.

**Comment by elliec** [comment]
@spMohanty thanks saw that, will close this one now
