### ISSUE TITLE
text size should be bigger

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#6]
Text size should be at least 13pts i think (weve already had one compaint that the text on the old site is too small)

The text for the category names is too small.

I think the text under find photos and analyse photos should probably be a bit bigger too

same for about project

**Comment by spMohanty** [comment]
@elliec : The font size was already 14px, and I increased it to 16px now.

**Comment by elliec** [comment]
@spMohanty : thanks thats fine
