### ISSUE TITLE
Support for GeoJSON in summary export

### ISSUE THREAD

**Issue by spMohanty** [geotagx/geotagx-theme#62]

**Comment by spMohanty** [comment]
Summary export has to be written for categories instead of projects (as all individual projects might not have a geolocation entry) (and summary export will only contain images for which atleast one geolocation entry has been recorded)

**Comment by spMohanty** [comment]
A very basic implementation is done using https://github.com/geotagx/pybossa/commit/0ed6131edf58d30f56d11004a8431aba526e0da8 and  https://github.com/geotagx/geotagx-theme/commit/85a504a2f9b0aebba79252b1b69cb9f04e50feb9 . Now you should see a "Export Summary as GeoJSON" button on the category page. Ex [http://geotagx.org/project/category/emergencyshelterassessmentinthemiddleeast/](http://geotagx.org/project/category/emergencyshelterassessmentinthemiddleeast)

**Comment by elliec** [comment]
@spMohanty has this been updated to have lat and long

**Comment by spMohanty** [comment]
Implemented in the commit : https://github.com/geotagx/pybossa/commit/7b1de513bcb66eebbfc79a84d85bb63c80a91dc9

And GeoJSON output validated at [GeoJSONLint.com](GeoJSONLint.com)
