### ISSUE TITLE
Serve cached,watermarked, web optimized versions of all the images

### ISSUE THREAD

**Issue by spMohanty** [geotagx/geotagx-theme#65]

**Comment by elliec** [comment]
@spMohanty what did we decide on in the end for this?

**Comment by spMohanty** [comment]
@elliec : The conclusion was, given the current infrastructure we have, it would not be possible to go ahead with this enhancement. While if we soon move to a distributed infrastructure on cern openstack, we can easily go ahead with this.

**Comment by elliec** [comment]
@spMohanty I am going to close this, if #81 is completed we can reopen it but i think for now we wont do it
