### ISSUE TITLE
Link to Blogs on the front page

### ISSUE THREAD

**Issue by spMohanty** [geotagx/geotagx-theme#68]

**Comment by spMohanty** [comment]
Implemented in the commits https://github.com/geotagx/geotagx-theme/commit/e13f30b09828309753989ff7c4252f36076106af and https://github.com/geotagx/pybossa/commit/f133519c3e994447f0fa7884eb37e08b1da2011f

Though, instead of squeezing it on the front page, a new page (with a corresponding menu item) has been added.

**Comment by elliec** [comment]
closed because i think what we have now is fine
