### ISSUE TITLE
email incorrect

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#7]
in th efind photos, dont use the "unosat@unitar.org" email, we dont have access to that. Could we create an e-group or something similar for geotag-x that will send to us all? I dont think we can do this at UNITAR, maybe via CERN? In the meantime you can put my email.

You can leave unosat@unitar.org as the general email at the bottom of the page for now

**Comment by spMohanty** [comment]
@elliec  : Temporarily replaced the email with your email id. And you can create a static group or a mailing list at CERN using this form here : https://espace.cern.ch/e-groups-help/Users%20Guide/Create%20a%20new%20static%20group.aspx

**Comment by spMohanty** [comment]
Created an e-group on CERN e-group services by the name `geotag-x@cern.ch`, and added Ellie and Lars to the e-group. Updated the email in the new geotag-x theme.
