### ISSUE TITLE
Use "GeoTag-X" consistently everywhere

### ISSUE THREAD

**Issue by spMohanty** [geotagx/geotagx-theme#72]
The repository uses "GeoTag-X" in some places, and "Geotag-X" in some places, it should use "GeoTag-X" consistently everywhere.

**Comment by spMohanty** [comment]
Updated most of the changes in the templates, but these files will still need to be dealt with. Leaving this for @supranove as it requires a working `pbs` instance to update those changes.

``` bash
projects/geotagx-project-ebola-geotag/project.json:
projects/geotagx-project-ebola-geotag/project.json:
projects/geotagx-project-middle-east-reach-geotag/project.json:
projects/geotagx-project-middle-east-reach-geotag/project.json:
projects/geotagx-project-yamuna-geotag-2013/project.json:
projects/geotagx-project-yamuna-geotag-2013/project.json:
projects/geotagx-project-yemen-geotag/long_description.md:Right
projects/geotagx-project-yemen-geotag/project.json:
projects/geotagx-project-yemen-geotag/project.json:
geotagx_create_categories.py.example:
```

**Comment by othieno** [comment]
@spMohanty thanks for updating the projects, I can do the pbs updates.

**Comment by elliec** [comment]
@supranove did this get updated in the end? can we close it?

**Comment by othieno** [comment]
@elliec yes it's done.
