### ISSUE TITLE
Setup a shadow project for all generic blog posts

### ISSUE THREAD

**Issue by spMohanty** [geotagx/geotagx-theme#74]
Set up a shadow project called as `geotagxblog` for pushing all generic blog posts. Make its category as `Under Development`, and add necessary exceptions so it doesnt look like a regular project page.

**Comment by spMohanty** [comment]
@elliec  : Generic sitewide blog posts can now be made at : http://geotagx.org/project/geotagxblog/new-blogpost

TODO: Add a link to the list of all generic blogs posts, and also a way to delete them on the blogs page.

**Comment by elliec** [comment]
ok thanks, will wait for valentina's testing before closing but looks good

**Comment by elliec** [comment]
this seems to be done and working fine
