### ISSUE TITLE
layout of "how do I get started"

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#8]
text should be bigger

the alignment of the text is a bit strange - eg the first line should go all the way across, analyse photos should be all the way to the left,

the feedback text should go all the way across

**Comment by spMohanty** [comment]
@elliec : I do not quite get the way you imagine the layout. We should probably take this up on a quick skype call later today.

**Comment by elliec** [comment]
@spMohanty : this is not high priority we can talk about it later
