### ISSUE TITLE
Blog rendering needs fixing

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#82]

**Comment by spMohanty** [comment]
Fixed in commits : https://github.com/geotagx/pybossa/commit/b7f6e1a0e8214ae9f39e0e9893a3bcd98bef33d1 and https://github.com/geotagx/geotagx-theme/commit/23087fc4839a23a8dc2cd675c73a243bc57a184f

**Comment by elliec** [comment]
@spMohanty looks good ill close this now
