### ISSUE TITLE
Feedback form

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#9]
if you have a good idea about how to collect feedback i would welcome it. I think you mentioned using an application within GeotagX? i would prefer not the use the lime survey but it was the quickest/easiest method when i needed to set it up.

Github has been suggested by others but I do not want to use github for general public feedback

**Comment by spMohanty** [comment]
@elliec : Made the feedback form appear as a popup like in the case of surveys. Let me know if this makes things any better, or if I should revert back to the old state.

**Comment by elliec** [comment]
looks great thanks
