### ISSUE TITLE
update UNITAR/UNOSAT logo

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#90]
see email from valentina with correct logo

**Comment by spMohanty** [comment]
@elliec , @Valentina : Updated the logo. Let me know if this works. (I think its a bit stretched, I tried bringing both the components in the logo a bit closer. Is it okay ? )

**Comment by elliec** [comment]
@spMohanty seperate unosat and unitar

**Comment by spMohanty** [comment]
done

**Comment by elliec** [comment]
thanks
