### ISSUE TITLE
Image not clear and I don’t know buttons confusing

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#91]
Feedback from GISCorps:
-   The not clear and the I don't know in meanings almost the same, I think it would be enough to use only one of those. 
  Gergely G. Puskas   puskasgergelyg@gmail.com
-   "I don't know" and "photo not clear" seem interchangeable in the tutorials  (crop identification tutorial says the answer is "photo not clear" for the question about method of cultivation where you can't tell from the photo. However, in the tour at the beginning, you are asked to select this if the photo is blurry, poor quality, or not clear.) This could be very confusing and result in poor data. 
  Emily Hultman   emily.hultman@gmail.com
-   The user needs a clear definition of the "Image not clear" button. I was not certain whether that literally meant that the 'image' was not clear as in its resolution, or 'not clear' as in the feature that we were being asked to identify could not be determined from the image. 
  Melanie Harris  melanietmharris@gmail.com

**Comment by elliec** [comment]
@supranove change tour text to say "Select this option is the image is not clear enough for you to answer the question"

**Comment by elliec** [comment]
or "Select this option if you cannot answer this question given what you can see in the image"

**Comment by elliec** [comment]
@supranove is this done? if so we can close it

**Comment by othieno** [comment]
@elliec Yep, this should be fine. I left it open in case we got feedback about the distinction still not being clear enough however that hasn't happened so I think the tour text's clear enough now.
