### ISSUE TITLE
Remove reference to second photo in tutorials

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-theme#95]
Could we remove the referecne to the second photo on the tutorials? none of them currently have one

Feedback from GISCorps
In the tutorials, I had difficulty viewing the photo after the first photo.  
Holly Richards Geospatial14@gmail.com

**Comment by elliec** [comment]
@supranove to plan how to implement this for when we do get a second photo in a tutorial

**Comment by elliec** [comment]
@supranove did you do this? i remember some discussion about it being done....

**Comment by elliec** [comment]
if so you can close it

**Comment by othieno** [comment]
@elliec Thought I had this done. It is now :)
